import React, { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  let number: number
  let boolean: boolean
  let string: string
  let any: any
  let n: number[] = [1, 2, 3]
  let a: any[] = [1, true, 'a', false]

  enum Colors { Red, Blue, Green }

  // type assertion
  let message
  message = 'abc'
  let endWithC = (message as string).endsWith('c')

  // interfaces
  interface Message {
    x: string,
    y: string
  }

  let setMessage = (messaging: Message) => {
    console.log(messaging)
  }

  setMessage({ x: 'hello', y: 'hello' })

  // classes
  class Messaging {

    constructor(public a?: string, public b?: string) {
 
    }

    message() {
      console.log("x: " + this.a + " " + "y: " + this.b )
    }
  }

  const m = new Messaging()
  m.message()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}

export default Home
